package com.fndong.customer;
// Generated Mar 14, 2016 3:23:43 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * Order generated by hbm2java
 */
public class Order implements java.io.Serializable {

	private Integer orderId;
	private Customer customer;
	private Date orderDate;
	private Float totalPrice;
	private Float paid;
	private Date date;

	public Order() {
	}

	public Order(Customer customer, Date date) {
		this.customer = customer;
		this.date = date;
	}

	public Order(Customer customer, Date orderDate, Float totalPrice, Float paid, Date date) {
		this.customer = customer;
		this.orderDate = orderDate;
		this.totalPrice = totalPrice;
		this.paid = paid;
		this.date = date;
	}

	public Integer getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public Date getOrderDate() {
		return this.orderDate;
	}

	public void setOrderDate(Date orderDate) {
		this.orderDate = orderDate;
	}

	public Float getTotalPrice() {
		return this.totalPrice;
	}

	public void setTotalPrice(Float totalPrice) {
		this.totalPrice = totalPrice;
	}

	public Float getPaid() {
		return this.paid;
	}

	public void setPaid(Float paid) {
		this.paid = paid;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

}
