package com.fndong.customer;
// Generated Mar 14, 2016 3:23:43 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer userId;
	private String password;
	private String name;
	private String email;
	private Set<UserDetails> userDetailses = new HashSet<UserDetails>(0);

	public User() {
	}

	public User(String password, String name, String email) {
		this.password = password;
		this.name = name;
		this.email = email;
	}

	public User(String password, String name, String email, Set<UserDetails> userDetailses) {
		this.password = password;
		this.name = name;
		this.email = email;
		this.userDetailses = userDetailses;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Set<UserDetails> getUserDetailses() {
		return this.userDetailses;
	}

	public void setUserDetailses(Set<UserDetails> userDetailses) {
		this.userDetailses = userDetailses;
	}

}
